# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/contract.git
    REF 4a4047f84a1a849f8e2737d8d4ceb71a739e2082
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
