# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/predef.git
    REF e1211a4ca467bb6512e99025772ca25afa8d6159
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
file(
    COPY "${SOURCE_PATH}/libs/predef/tools/check"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/boost-predef"
)
