# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/ratio.git
    REF 6eceadad2eb04f00b8cae5e400f7bee34c2d501f
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
