set(CEF_PREV_MODULE_PATH ${CMAKE_MODULE_PATH})

set(CEF_ROOT "${CMAKE_CURRENT_LIST_DIR}/cef-root")
list(APPEND CMAKE_MODULE_PATH "${CEF_ROOT}/cmake")

_find_package(${ARGS})

set(CMAKE_MODULE_PATH ${CEF_PREV_MODULE_PATH})
