# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/spirit.git
    REF 82184fecd6e6979e44a539bb5ff0918724948c40
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
