# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/config.git
    REF a7d5a9b05d70c9cfea980dc3539ca3d3461411b3
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
file(APPEND
    "${CURRENT_PACKAGES_DIR}/include/boost/config/user.hpp"
    "\n#ifndef BOOST_ALL_NO_LIB\n#define BOOST_ALL_NO_LIB\n#endif\n"
)
file(APPEND
    "${CURRENT_PACKAGES_DIR}/include/boost/config/user.hpp"
    "\n#undef BOOST_ALL_DYN_LINK\n"
)

if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    file(APPEND
        "${CURRENT_PACKAGES_DIR}/include/boost/config/user.hpp"
        "\n#define BOOST_ALL_DYN_LINK\n"
    )
endif()

file(
    COPY "${SOURCE_PATH}/libs/config/checks"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/boost-config"
)
