# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:boostorg/icl.git
    REF 2741c3a1b7b79f7326360c26c3e1588b385c9e53
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
